  
language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules
  yarn: true

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  email: 545660146@qq.com
  name: ambigudus
  target-branch: gh-pages
  on:
    branch: master